### PR TITLE
Letting users reset Search by removing error for blank search

### PR DESCRIPTION
**Pull request by HiltonGiesenow**
Possible fix for issue 319, to allow users to reset Search for Templates

### CODE REVIEW

**Comment by PaoloPia** [comment]
Hi @HiltonGiesenow,
Thanks for your contribution. Can you expand a little bit more about this fix? I just see that you removed code, which actually should be there. Thanks.

**Comment by HiltonGiesenow** [comment]
Hey Paolo,

Sure thing. Basically, I realised there's no way to "reset" search - if you've searched for a term, but you want instead to go back and see the entire catalog again, you actually need to F5 refresh the entire page. So, I guess two options are to either (a) add a "reset" or "clear" button, or (b) just to let people execute a "blank" search, which is the option I went for here.

I logged an issue for this also, just fyi - #320

**Comment by PaoloPia** [comment]
Hi @HiltonGiesenow,
Thanks for your comment. Actually, I cannot merge this PR "as is" because you are removing some of the logic that is in the JS file. Please, provide a different solution, like a reset button. Thanks.

**Comment by HiltonGiesenow** [comment]
Thanks Paolo, I'll look into it, just massively heads down at the moment.

**Pull request closed without merging**
