### PR TITLE
Update doco

### PR DESCRIPTION
**Pull request by camiloborges**
updated Manual Steps guide. 
The steps are in a different order, which streamlines the manual process.
Can and possibly should also have PowerShell calls as an option to perform the configuration.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Camilo, we will process this in upcoming weeks due resourcing challenges, but we'll absolutely have closer look on this, since feedback is valid and current instructions could be challenging to follow.

**Comment by PaoloPia** [comment]
Thanks Camilo,
The PR has been merged.

**Comment by camiloborges** [comment]
What an honour! Thank you. 
Please let me know if I could have made it any easier since I noticed your other PR mentioning conflicts.

**Comment by PaoloPia** [comment]
No worries Camillo, I had to handle some conflicts between your updates and someone else's updates, but it is a common issue. You did it right. Thanks again.

**Pull request merged**
