### PR TITLE
[WIP] Support Multilingual UI

### PR DESCRIPTION
**Pull request by biste5**
Adds support for Multilingual UI, based on site's language for sub site creation UI
Reference: #214 

Kudos to @amirkhanRC that has done most of the initial job.

**Work in Progress**
I still have some work to ensure, before you can start merging this PR

### CODE REVIEW

**Comment by biste5** [comment]
I think this PR can now be merged.
The base implementation for UI should be in place.

Things to mention:
- Localization of JavaScript resources isn't complete (help is welcome)
- In order to have the new feature to work correcly, PnP Partner Pack must be de-activated, and activated again on site where it was already active

**Comment by PaoloPia** [comment]
Hi Massimo,
Thanks for your contribution. It is a big PR (26 files), so it will take a while to evaluate it, but I'm already working on it.

**Comment by PaoloPia** [comment]
Hi Massimo,
Thanks again for your contribution. I tested it in my dev environment and I have some feedbacks for you. First, I really love to see the PnP Partner Pack in multiple languages :-) ... it's great. Thanks!

However, with the current implementation in this PR there are some messages that get translated and some others that do not get translated. I would ask you, if you can, to complete the implementation, providing support for Model properties (for example using a custom DisplayNameLocalizedAttribute), as well as for some other fields that are not yet translated. Having the UI half in ITA and half in ENG does not provide a good UX to the end users. Moreover, we should make it possible to intercept the current user's language, using Microsoft Graph, and provide the UI by default with that language, instead of having a dropdown list to choose the language from or a querystring parameter stored in the Session object.

The PnP Partner Pack is used by a huge number of companies, and we cannot ship a partial support for multi-language like this, but the idea and the implementation are really good. It simply need some final adjustements. Thus, if you can take care of these final tasks, I will be more than happy to merge the updated PR. Thanks.

**Comment by biste5** [comment]
Hi Paolo,
I understand your feedback. Shortly, I recap two issues on making a full good translation
- Localization of JS resources (as mentioned in the PR), requiring creation of an extra controller and a bit of time to do it properly
- Office UI JS components used by the solution (they don't support localization, so what about that?)

so at that time I preferred to commit a working initial base because I'm not sure how much time I'll have to dedicate on completing this in short, and so was looking for some help.

Your idea about retrieving user's language from Graph is for sure good, but a further addition

If I understand and I help you recap the missing steps for a good multi-lingual solution:
- Localize all UI strings visible to end users (incl. JS strings)
- Localize all UI strings visible to end users including admin interfaces (such as governance), and JS strings
- Set UI language by retrieving user's preferred language from Graph

I can rename the PR as work in progress, but I'm not sure in which timeline I could implement the above

**Comment by PaoloPia** [comment]
Hi Massimo,
Based on the resources (time) that we have right now, it would be great if you can take care of completing this PR, based on your own availability and time. Just let me know an approx timeline, if you can. Thank you very much.

**Comment by PaoloPia** [comment]
Hi Massimo,
Are you still working on this or can I close it? Thanks.

**Comment by biste5** [comment]
Hi Paolo,

I haven't had anymore chance to improve and finish up the localization.
Also, I don't think this can happen in short, so I'll close the PR for now.

Massimo

**Pull request closed without merging**
