### PR TITLE
Creating Pull Request for Composed Looks update

### PR DESCRIPTION
**Pull request by jkovach82**

### CODE REVIEW

**Comment by jkovach82** [comment]
For clarification this pull request is to add functionality so the composed looks are gathered from an individual site collection and does not utilize the built-in branding functionality.

**Comment by PaoloPia** [comment]
Hi @jkovach82,
Thanks for your contribution. Can you expand a little bit more on this proposed change? Thanks.

**Comment by jkovach82** [comment]
The default behavior of the Partner Pack appears to apply tenant branding to any site with the Persist Composed Looks set to enabled.  However this limits the ability to have individual branding at the site template level.  For example you might want your intranet pages to look, feel and behave differently than a work group's team site.  

The proposed change will allow users to configure Composed Looks on a site and then use the Partner Pack to extract the site features as well as the currently applied composed look.  The user may also supply override files to replace the composed look currently applied to the site. This replaces the current functionality of the Tenant Branding for a more localized Site Branding approach.

**Comment by PaoloPia** [comment]
Hi @jkovach82,
We discussed internally your proposal and we would like to have it as an additional option, rather than as a replacement of an existing capability. Can you slightly adapt this PR accordingly?
BTW, I just noticed that you targeted the master branch, but we do not accept PRs against master. Thus, could you please target the dev branch with the updated PR? In the meantime, I will close this item.

Thanks.

**Comment by jkovach82** [comment]
I was actually thinking the same thing maybe I will have two switches, one for Tenant Branding and one for Local Site Branding.  Apologize about the master branch pull, still very new to Git.  About a year ago I purchased a copy of your Programming for O365 book and found it very informative, great hearing from you have a good day.

---

Joseph D. Kovach
________________________________

**Pull request closed without merging**
